# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodbData:/data/db
      - ./dataset:/dataset/
    ports:
      - 27017:27017
    networks:
      - mongodbnet
volumes:
  mongodbData:
    driver: local
networks:
  mongodbnet: